edition = "2021"

use_small_heuristics = "Max"
max_width = 140
chain_width = 120
single_line_if_else_max_width = 100
reorder_imports = true
merge_derives = false
match_block_trailing_comma = true
fn_params_layout = "Compressed"

# Reorder mod declarations alphabetically in group.
reorder_modules = true


# Force multiline closure and match arm bodies to be wrapped in a block
# https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=#force_multiline_blocks
# force_multiline_blocks = true


