version = "Two"

format_strings = true
hex_literal_case = "Upper"

use_small_heuristics = "Max"
max_width = 140
chain_width = 120
single_line_if_else_max_width = 100


reorder_imports = true
group_imports = "StdExternalCrate"
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
merge_imports = true


merge_derives = false
format_macro_matchers = true

match_block_trailing_comma = true
fn_params_layout = "Compressed"


# Reorder impl items. type and const are put first, then macros and methods.
reorder_impl_items = true

# Reorder mod declarations alphabetically in group.
reorder_modules = true


# Force multiline closure and match arm bodies to be wrapped in a block
# https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=#force_multiline_blocks
# force_multiline_blocks = true


