name: logos
short: LOGO
debug: false

webs:
  - name: api
    port: 8080

model:
  backends:
    - name: postgre
      kind: postgres
      readonly: false
      connect: ""
    - name: redis
      kind: redis
      readonly: false
      connect: ""