name: logos
short: LOGO
debug: false

web:
  api:
    port: 8080
    middleware:
      signator:
        redis_url: "redis://127.0.0.1"

model:
  backends:
    postgre:
      kind: postgres
      readonly: false
      connect: ""
    redis:
      kind: redis
      readonly: false
      connect: ""