//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("logos")
    }
    fn table_name(&self) -> &str {
        "cn_region"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub parent: i64,
    pub level: i16,
    pub code: i64,
    pub name: String,
    pub spelling: String,
    pub partial: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Parent,
    Level,
    Code,
    Name,
    Spelling,
    Partial,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Parent => ColumnType::BigInteger.def(),
            Self::Level => ColumnType::SmallInteger.def(),
            Self::Code => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Spelling => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Partial => ColumnType::String(StringLen::N(255u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
