//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("logos")
    }
    fn table_name(&self) -> &str {
        "user_bind"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub uid: i64,
    pub platform: String,
    pub proof: Json,
    pub expire_at: DateTime,
    pub device: Json,
    pub state: i32,
    pub created: DateTime,
    pub updated: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Uid,
    Platform,
    Proof,
    ExpireAt,
    Device,
    State,
    Created,
    Updated,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Uid => ColumnType::BigInteger.def(),
            Self::Platform => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Proof => ColumnType::JsonBinary.def(),
            Self::ExpireAt => ColumnType::DateTime.def(),
            Self::Device => ColumnType::JsonBinary.def(),
            Self::State => ColumnType::Integer.def(),
            Self::Created => ColumnType::DateTime.def(),
            Self::Updated => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
