[package]
name = "rexamples"
version = "0.1.0"
edition = "2021"

[dependencies]
rings = { path = "../." }
ringm = { path = "../ringm" , features = ["use_func_register"]}
ringb = { path = "../ringb" }
