[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
rings = { workspace = true }
service = { path = "../service" }
serde = { version = "1.0.219", features = ["derive"] }
axum = "0.8"